/* Generated by Pyrex 0.9.8.5 on Sat Dec 25 21:24:28 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "errno.h"
#include "stdlib.h"
#include "sys/types.h"
#include "sys/socket.h"
#include "linux/netlink.h"
#include "linux/connector.h"
#include "linux/cn_proc.h"
#include "string.h"
#include "unistd.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from debathena.metrics.connector */


/* Declarations from implementation of debathena.metrics.connector */

struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent {
  PyObject_HEAD
  long what;
  long cpu;
  long timestamp_ns;
};

struct __pyx_obj_9debathena_7metrics_9connector_AckProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
  long err;
};

struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
  long parent_pid;
  long parent_tgid;
  long child_pid;
  long child_tgid;
};

struct __pyx_obj_9debathena_7metrics_9connector_ExecProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
  long process_pid;
  long process_tgid;
};

struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
  long process_pid;
  long process_tgid;
  long ruid;
  long euid;
};

struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
  long process_pid;
  long process_tgid;
  long rgid;
  long egid;
};

struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
  long process_pid;
  long process_tgid;
  long exit_code;
  long exit_signal;
};

struct __pyx_obj_9debathena_7metrics_9connector_UnknownProcEvent {
  struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent __pyx_base;
};

struct __pyx_obj_9debathena_7metrics_9connector_Connector {
  PyObject_HEAD
  int sock;
  PyObject *closed;
};










static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_ProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_AckProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_ForkProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_ExecProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_UidProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_GidProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_ExitProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_UnknownProcEvent = 0;
static PyTypeObject *__pyx_ptype_9debathena_7metrics_9connector_Connector = 0;

static char __pyx_k1[] = "<AckProcEvent err=%d>";
static char __pyx_k2[] = "<ForkProcEvent ppid=%d ptgid=%d pid=%d tgid=%d>";
static char __pyx_k3[] = "<ExecProcEvent pid=%d tgid=%d>";
static char __pyx_k4[] = "<UidProcEvent pid=%d tgid=%d ruid=%d euid=%d>";
static char __pyx_k5[] = "<GidProcEvent pid=%d tgid=%d rgid=%d egid=%d>";
static char __pyx_k6[] = "<ExitProcEvent pid=%d tgid=%d code=%d signal=%d>";
static char __pyx_k7[] = "<UnknownProcEvent what=%d>";
static char __pyx_k8[] = "PROC_EVENT_FORK";
static char __pyx_k9[] = "parent_pid";
static char __pyx_k10[] = "parent_tgid";
static char __pyx_k11[] = "child_pid";
static char __pyx_k12[] = "child_tgid";
static char __pyx_k13[] = "PROC_EVENT_EXEC";
static char __pyx_k14[] = "process_pid";
static char __pyx_k15[] = "process_tgid";
static char __pyx_k16[] = "PROC_EVENT_UID";
static char __pyx_k17[] = "ruid";
static char __pyx_k18[] = "euid";
static char __pyx_k19[] = "PROC_EVENT_GID";
static char __pyx_k20[] = "rgid";
static char __pyx_k21[] = "egid";
static char __pyx_k22[] = "PROC_EVENT_EXIT";
static char __pyx_k23[] = "exit_code";
static char __pyx_k24[] = "exit_signal";
static char __pyx_k25[] = "what";
static char __pyx_k26[] = "cpu";
static char __pyx_k27[] = "timestamp_ns";
static char __pyx_k28[] = "PROC_EVENT_NONE";

static PyObject *__pyx_n_PROC_EVENT_EXEC;
static PyObject *__pyx_n_PROC_EVENT_EXIT;
static PyObject *__pyx_n_PROC_EVENT_FORK;
static PyObject *__pyx_n_PROC_EVENT_GID;
static PyObject *__pyx_n_PROC_EVENT_NONE;
static PyObject *__pyx_n_PROC_EVENT_UID;
static PyObject *__pyx_n_child_pid;
static PyObject *__pyx_n_child_tgid;
static PyObject *__pyx_n_cpu;
static PyObject *__pyx_n_egid;
static PyObject *__pyx_n_euid;
static PyObject *__pyx_n_exit_code;
static PyObject *__pyx_n_exit_signal;
static PyObject *__pyx_n_parent_pid;
static PyObject *__pyx_n_parent_tgid;
static PyObject *__pyx_n_process_pid;
static PyObject *__pyx_n_process_tgid;
static PyObject *__pyx_n_rgid;
static PyObject *__pyx_n_ruid;
static PyObject *__pyx_n_timestamp_ns;
static PyObject *__pyx_n_what;

static PyObject *__pyx_k1p;
static PyObject *__pyx_k2p;
static PyObject *__pyx_k3p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k5p;
static PyObject *__pyx_k6p;
static PyObject *__pyx_k7p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_PROC_EVENT_EXEC, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_PROC_EVENT_EXIT, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_PROC_EVENT_FORK, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_PROC_EVENT_GID, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_PROC_EVENT_NONE, 1, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_n_PROC_EVENT_UID, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_child_pid, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_child_tgid, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_cpu, 1, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_n_egid, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_euid, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_exit_code, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_exit_signal, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_parent_pid, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_parent_tgid, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_process_pid, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_process_tgid, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_rgid, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_ruid, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_timestamp_ns, 1, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_n_what, 1, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_k1p, 0, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_k2p, 0, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k5p, 0, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {0, 0, 0, 0}
};



/* Implementation of debathena.metrics.connector */

static PyObject *__pyx_f_9debathena_7metrics_9connector_12AckProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_12AckProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_AckProcEvent *)__pyx_v_self)->err); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_k1p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 137; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("debathena.metrics.connector.AckProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_13ForkProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_13ForkProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent *)__pyx_v_self)->parent_pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent *)__pyx_v_self)->parent_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent *)__pyx_v_self)->child_pid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent *)__pyx_v_self)->child_tgid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k2p, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("debathena.metrics.connector.ForkProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_13ExecProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_13ExecProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ExecProcEvent *)__pyx_v_self)->process_pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ExecProcEvent *)__pyx_v_self)->process_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 161; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 160; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k3p, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 159; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("debathena.metrics.connector.ExecProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_12UidProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_12UidProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent *)__pyx_v_self)->process_pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent *)__pyx_v_self)->process_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent *)__pyx_v_self)->ruid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 174; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent *)__pyx_v_self)->euid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 175; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 172; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k4p, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("debathena.metrics.connector.UidProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_12GidProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_12GidProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent *)__pyx_v_self)->process_pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent *)__pyx_v_self)->process_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent *)__pyx_v_self)->rgid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 188; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent *)__pyx_v_self)->egid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 189; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k5p, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("debathena.metrics.connector.GidProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_13ExitProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_13ExitProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent *)__pyx_v_self)->process_pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent *)__pyx_v_self)->process_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent *)__pyx_v_self)->exit_code); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent *)__pyx_v_self)->exit_signal); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(4); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
  PyTuple_SET_ITEM(__pyx_5, 2, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 3, __pyx_4);
  __pyx_1 = 0;
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_1 = PyNumber_Remainder(__pyx_k6p, __pyx_5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 199; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("debathena.metrics.connector.ExitProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_16UnknownProcEvent___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_16UnknownProcEvent___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF((PyObject *)__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_UnknownProcEvent *)__pyx_v_self)->__pyx_base.what); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_k7p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 208; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("debathena.metrics.connector.UnknownProcEvent.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF((PyObject *)__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_9debathena_7metrics_9connector_9Connector___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9debathena_7metrics_9connector_9Connector___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct sockaddr_nl __pyx_v_my_addr;
  char __pyx_v_buf[4096];
  struct nlmsghdr *__pyx_v_nl_hdr;
  struct cn_msg *__pyx_v_cn_hdr;
  enum proc_cn_mcast_op *__pyx_v_mcop_msg;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":216 */
  Py_INCREF(Py_False);
  Py_DECREF(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->closed);
  ((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->closed = Py_False;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":225 */
  ((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock = socket(PF_NETLINK,SOCK_DGRAM,NETLINK_CONNECTOR);

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":227 */
  __pyx_v_my_addr.nl_family = AF_NETLINK;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":228 */
  __pyx_v_my_addr.nl_groups = CN_IDX_PROC;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":229 */
  __pyx_v_my_addr.nl_pid = getpid();

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":231 */
  __pyx_1 = (bind(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock,((struct sockaddr *)(&__pyx_v_my_addr)),(sizeof(__pyx_v_my_addr))) < 0);
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong(errno); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 232; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(strerror(errno)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 232; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 232; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(PyExc_IOError, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 232; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 232; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":234 */
  __pyx_v_nl_hdr = ((struct nlmsghdr *)__pyx_v_buf);

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":235 */
  __pyx_v_nl_hdr->nlmsg_len = NLMSG_LENGTH(((sizeof(struct cn_msg)) + (sizeof(enum proc_cn_mcast_op))));

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":236 */
  __pyx_v_nl_hdr->nlmsg_type = NLMSG_DONE;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":237 */
  __pyx_v_nl_hdr->nlmsg_flags = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":238 */
  __pyx_v_nl_hdr->nlmsg_seq = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":239 */
  __pyx_v_nl_hdr->nlmsg_pid = getpid();

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":241 */
  __pyx_v_cn_hdr = ((struct cn_msg *)NLMSG_DATA(__pyx_v_nl_hdr));

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":242 */
  __pyx_v_cn_hdr->id.idx = CN_IDX_PROC;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":243 */
  __pyx_v_cn_hdr->id.val = CN_VAL_PROC;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":244 */
  __pyx_v_cn_hdr->seq = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":245 */
  __pyx_v_cn_hdr->ack = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":246 */
  __pyx_v_cn_hdr->len = (sizeof(enum proc_cn_mcast_op));

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":248 */
  __pyx_v_mcop_msg = ((enum proc_cn_mcast_op *)__pyx_v_cn_hdr->data);

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":249 */
  (__pyx_v_mcop_msg[0]) = PROC_CN_MCAST_LISTEN;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":251 */
  __pyx_1 = (send(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock,__pyx_v_nl_hdr,__pyx_v_nl_hdr->nlmsg_len,0) != __pyx_v_nl_hdr->nlmsg_len);
  if (__pyx_1) {
    __pyx_3 = PyInt_FromLong(errno); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
    __pyx_4 = PyString_FromString(strerror(errno)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_2, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyObject_CallObject(PyExc_IOError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 252; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("debathena.metrics.connector.Connector.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_9debathena_7metrics_9connector_9Connector___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_9debathena_7metrics_9connector_9Connector___dealloc__(PyObject *__pyx_v_self) {
  int __pyx_1;
  int __pyx_2;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_IsTrue(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->closed); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 255; goto __pyx_L1;}
  __pyx_2 = (!__pyx_1);
  if (__pyx_2) {
    close(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock);
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("debathena.metrics.connector.Connector.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_9Connector_fileno(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_9Connector_fileno(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 259; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("debathena.metrics.connector.Connector.fileno");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_9Connector_close(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_9Connector_close(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyObject_IsTrue(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->closed); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 262; goto __pyx_L1;}
  __pyx_2 = (!__pyx_1);
  if (__pyx_2) {

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":263 */
    close(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock);

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":264 */
    Py_INCREF(Py_True);
    Py_DECREF(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->closed);
    ((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->closed = Py_True;
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("debathena.metrics.connector.Connector.close");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9debathena_7metrics_9connector_9Connector_recv_event(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9debathena_7metrics_9connector_9Connector_recv_event(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char __pyx_v_buf[4096];
  struct sockaddr_nl __pyx_v_from_addr;
  socklen_t __pyx_v_s;
  struct proc_event *__pyx_v_ev;
  PyObject *__pyx_v_ret;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_ret = Py_None; Py_INCREF(Py_None);

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":273 */
  __pyx_v_from_addr.nl_family = AF_NETLINK;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":274 */
  __pyx_v_from_addr.nl_groups = CN_IDX_PROC;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":275 */
  __pyx_v_from_addr.nl_pid = 1;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":276 */
  __pyx_v_s = (sizeof(__pyx_v_from_addr));

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":278 */
  __pyx_1 = (recvfrom(((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)__pyx_v_self)->sock,__pyx_v_buf,(sizeof(__pyx_v_buf)),0,((struct sockaddr *)(&__pyx_v_from_addr)),(&__pyx_v_s)) == (-1));
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong(errno); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(strerror(errno)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyObject_CallObject(PyExc_IOError, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":282 */
  __pyx_v_ev = ((struct proc_event *)((struct cn_msg *)NLMSG_DATA(__pyx_v_buf))->data);

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":284 */
  __pyx_3 = PyInt_FromLong(__pyx_v_ev->what); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 284; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_PROC_EVENT_FORK); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 284; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_3, __pyx_4, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 284; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_1) {

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":285 */
    __pyx_2 = PyObject_CallObject(((PyObject *)__pyx_ptype_9debathena_7metrics_9connector_ForkProcEvent), 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 285; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_2;
    __pyx_2 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":286 */
    __pyx_3 = PyInt_FromLong(__pyx_v_ev->event_data.fork.parent_pid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 286; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_parent_pid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 286; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":287 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ev->event_data.fork.parent_tgid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 287; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_parent_tgid, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 287; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":288 */
    __pyx_2 = PyInt_FromLong(__pyx_v_ev->event_data.fork.child_pid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 288; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_child_pid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 288; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":289 */
    __pyx_3 = PyInt_FromLong(__pyx_v_ev->event_data.fork.child_tgid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_child_tgid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 289; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L3;
  }
  __pyx_4 = PyInt_FromLong(__pyx_v_ev->what); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 290; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_PROC_EVENT_EXEC); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 290; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_4, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 290; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_1) {

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":291 */
    __pyx_3 = PyObject_CallObject(((PyObject *)__pyx_ptype_9debathena_7metrics_9connector_ExecProcEvent), 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 291; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_3;
    __pyx_3 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":292 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ev->event_data.exec.process_pid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 292; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_pid, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 292; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":293 */
    __pyx_2 = PyInt_FromLong(__pyx_v_ev->event_data.exec.process_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 293; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_tgid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 293; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L3;
  }
  __pyx_3 = PyInt_FromLong(__pyx_v_ev->what); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_PROC_EVENT_UID); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_3, __pyx_4, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (__pyx_1) {

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":295 */
    __pyx_2 = PyObject_CallObject(((PyObject *)__pyx_ptype_9debathena_7metrics_9connector_UidProcEvent), 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 295; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_2;
    __pyx_2 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":296 */
    __pyx_3 = PyInt_FromLong(__pyx_v_ev->event_data.id.process_pid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 296; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_pid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 296; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":297 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ev->event_data.id.process_tgid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 297; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_tgid, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 297; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":298 */
    __pyx_2 = PyInt_FromLong(__pyx_v_ev->event_data.id.r.ruid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 298; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_ruid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 298; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":299 */
    __pyx_3 = PyInt_FromLong(__pyx_v_ev->event_data.id.e.euid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 299; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_euid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 299; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L3;
  }
  __pyx_4 = PyInt_FromLong(__pyx_v_ev->what); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 300; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_PROC_EVENT_GID); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 300; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_4, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 300; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_1) {

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":301 */
    __pyx_3 = PyObject_CallObject(((PyObject *)__pyx_ptype_9debathena_7metrics_9connector_GidProcEvent), 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 301; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_3;
    __pyx_3 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":302 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ev->event_data.id.process_pid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 302; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_pid, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 302; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":303 */
    __pyx_2 = PyInt_FromLong(__pyx_v_ev->event_data.id.process_tgid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_tgid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 303; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":304 */
    __pyx_3 = PyInt_FromLong(__pyx_v_ev->event_data.id.r.rgid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 304; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_rgid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 304; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":305 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ev->event_data.id.e.egid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 305; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_egid, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 305; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L3;
  }
  __pyx_2 = PyInt_FromLong(__pyx_v_ev->what); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_PROC_EVENT_EXIT); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  if (PyObject_Cmp(__pyx_2, __pyx_3, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 306; goto __pyx_L1;}
  __pyx_1 = __pyx_1 == 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_1) {

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":307 */
    __pyx_4 = PyObject_CallObject(((PyObject *)__pyx_ptype_9debathena_7metrics_9connector_ExitProcEvent), 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 307; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_4;
    __pyx_4 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":308 */
    __pyx_2 = PyInt_FromLong(__pyx_v_ev->event_data.exit.process_pid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_pid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":309 */
    __pyx_3 = PyInt_FromLong(__pyx_v_ev->event_data.exit.process_tgid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 309; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_process_tgid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 309; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":310 */
    __pyx_4 = PyInt_FromLong(__pyx_v_ev->event_data.exit.exit_code); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_exit_code, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 310; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":311 */
    __pyx_2 = PyInt_FromLong(__pyx_v_ev->event_data.exit.exit_signal); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 311; goto __pyx_L1;}
    if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_exit_signal, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 311; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L3;
  }
  /*else*/ {
    __pyx_3 = PyObject_CallObject(((PyObject *)__pyx_ptype_9debathena_7metrics_9connector_UnknownProcEvent), 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 313; goto __pyx_L1;}
    Py_DECREF(__pyx_v_ret);
    __pyx_v_ret = __pyx_3;
    __pyx_3 = 0;
  }
  __pyx_L3:;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":315 */
  __pyx_4 = PyInt_FromLong(__pyx_v_ev->what); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 315; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_what, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 315; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":316 */
  __pyx_2 = PyInt_FromLong(__pyx_v_ev->cpu); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 316; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_cpu, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 316; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":317 */
  __pyx_3 = PyInt_FromLong(__pyx_v_ev->timestamp_ns); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 317; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_ret, __pyx_n_timestamp_ns, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 317; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":319 */
  Py_INCREF(__pyx_v_ret);
  __pyx_r = __pyx_v_ret;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("debathena.metrics.connector.Connector.recv_event");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ret);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_ProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_ProcEvent(PyObject *o) {
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_ProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_ProcEvent[] = {
  {"what", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent, what), 0, 0},
  {"cpu", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent, cpu), 0, 0},
  {"timestamp_ns", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent, timestamp_ns), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_ProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_ProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.ProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_ProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_ProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_ProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_ProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_ProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_ProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_ProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_AckProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_AckProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_AckProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_AckProcEvent[] = {
  {"err", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_AckProcEvent, err), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_AckProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_AckProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_AckProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_AckProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_AckProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.AckProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_AckProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_AckProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_12AckProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_AckProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_AckProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_AckProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_AckProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_AckProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_AckProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_AckProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_ForkProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_ForkProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_ForkProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_ForkProcEvent[] = {
  {"parent_pid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent, parent_pid), 0, 0},
  {"parent_tgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent, parent_tgid), 0, 0},
  {"child_pid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent, child_pid), 0, 0},
  {"child_tgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent, child_tgid), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ForkProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_ForkProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ForkProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ForkProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_ForkProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.ForkProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_ForkProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_ForkProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_13ForkProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_ForkProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_ForkProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ForkProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ForkProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_ForkProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_ForkProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_ForkProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_ExecProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_ExecProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_ExecProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_ExecProcEvent[] = {
  {"process_pid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ExecProcEvent, process_pid), 0, 0},
  {"process_tgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ExecProcEvent, process_tgid), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ExecProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_ExecProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ExecProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ExecProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_ExecProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.ExecProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_ExecProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_ExecProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_13ExecProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_ExecProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_ExecProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ExecProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ExecProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_ExecProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_ExecProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_ExecProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_UidProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_UidProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_UidProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_UidProcEvent[] = {
  {"process_pid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent, process_pid), 0, 0},
  {"process_tgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent, process_tgid), 0, 0},
  {"ruid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent, ruid), 0, 0},
  {"euid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent, euid), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_UidProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_UidProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_UidProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_UidProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_UidProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.UidProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_UidProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_UidProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_12UidProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_UidProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_UidProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_UidProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_UidProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_UidProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_UidProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_UidProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_GidProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_GidProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_GidProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_GidProcEvent[] = {
  {"process_pid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent, process_pid), 0, 0},
  {"process_tgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent, process_tgid), 0, 0},
  {"rgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent, rgid), 0, 0},
  {"egid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent, egid), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_GidProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_GidProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_GidProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_GidProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_GidProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.GidProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_GidProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_GidProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_12GidProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_GidProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_GidProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_GidProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_GidProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_GidProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_GidProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_GidProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_ExitProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_ExitProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_ExitProcEvent[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_ExitProcEvent[] = {
  {"process_pid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent, process_pid), 0, 0},
  {"process_tgid", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent, process_tgid), 0, 0},
  {"exit_code", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent, exit_code), 0, 0},
  {"exit_signal", T_LONG, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent, exit_signal), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ExitProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_ExitProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ExitProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ExitProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_ExitProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.ExitProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_ExitProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_ExitProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_13ExitProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_ExitProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_ExitProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ExitProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ExitProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_ExitProcEvent, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_ExitProcEvent, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_ExitProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_UnknownProcEvent(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_UnknownProcEvent(PyObject *o) {
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_UnknownProcEvent[] = {
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_UnknownProcEvent = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_UnknownProcEvent = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_UnknownProcEvent = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_UnknownProcEvent = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_UnknownProcEvent = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.UnknownProcEvent", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_UnknownProcEvent), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_UnknownProcEvent, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_f_9debathena_7metrics_9connector_16UnknownProcEvent___repr__, /*tp_repr*/
  &__pyx_tp_as_number_UnknownProcEvent, /*tp_as_number*/
  &__pyx_tp_as_sequence_UnknownProcEvent, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_UnknownProcEvent, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_UnknownProcEvent, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_UnknownProcEvent, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_UnknownProcEvent, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_9debathena_7metrics_9connector_Connector(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9debathena_7metrics_9connector_Connector *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_9debathena_7metrics_9connector_Connector *)o);
  p->closed = Py_None; Py_INCREF(Py_None);
  if (__pyx_f_9debathena_7metrics_9connector_9Connector___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_9debathena_7metrics_9connector_Connector(PyObject *o) {
  struct __pyx_obj_9debathena_7metrics_9connector_Connector *p = (struct __pyx_obj_9debathena_7metrics_9connector_Connector *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_9debathena_7metrics_9connector_9Connector___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->closed);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9debathena_7metrics_9connector_Connector(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_9debathena_7metrics_9connector_Connector *p = (struct __pyx_obj_9debathena_7metrics_9connector_Connector *)o;
  if (p->closed) {
    e = (*v)(p->closed, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_9debathena_7metrics_9connector_Connector(PyObject *o) {
  struct __pyx_obj_9debathena_7metrics_9connector_Connector *p = (struct __pyx_obj_9debathena_7metrics_9connector_Connector *)o;
  PyObject *t;
  t = p->closed; 
  p->closed = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_9debathena_7metrics_9connector_Connector[] = {
  {"fileno", (PyCFunction)__pyx_f_9debathena_7metrics_9connector_9Connector_fileno, METH_VARARGS|METH_KEYWORDS, 0},
  {"close", (PyCFunction)__pyx_f_9debathena_7metrics_9connector_9Connector_close, METH_VARARGS|METH_KEYWORDS, 0},
  {"recv_event", (PyCFunction)__pyx_f_9debathena_7metrics_9connector_9Connector_recv_event, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_9debathena_7metrics_9connector_Connector[] = {
  {"closed", T_OBJECT, offsetof(struct __pyx_obj_9debathena_7metrics_9connector_Connector, closed), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Connector = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Connector = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Connector = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Connector = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9debathena_7metrics_9connector_Connector = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "debathena.metrics.connector.Connector", /*tp_name*/
  sizeof(struct __pyx_obj_9debathena_7metrics_9connector_Connector), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9debathena_7metrics_9connector_Connector, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Connector, /*tp_as_number*/
  &__pyx_tp_as_sequence_Connector, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Connector, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Connector, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9debathena_7metrics_9connector_Connector, /*tp_traverse*/
  __pyx_tp_clear_9debathena_7metrics_9connector_Connector, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9debathena_7metrics_9connector_Connector, /*tp_methods*/
  __pyx_members_9debathena_7metrics_9connector_Connector, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9debathena_7metrics_9connector_Connector, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initconnector(void); /*proto*/
PyMODINIT_FUNC initconnector(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("connector", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_ProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_ProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_ProcEvent = &__pyx_type_9debathena_7metrics_9connector_ProcEvent;
  __pyx_type_9debathena_7metrics_9connector_AckProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_AckProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "AckProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_AckProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_AckProcEvent = &__pyx_type_9debathena_7metrics_9connector_AckProcEvent;
  __pyx_type_9debathena_7metrics_9connector_ForkProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_ForkProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ForkProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_ForkProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_ForkProcEvent = &__pyx_type_9debathena_7metrics_9connector_ForkProcEvent;
  __pyx_type_9debathena_7metrics_9connector_ExecProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_ExecProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ExecProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_ExecProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_ExecProcEvent = &__pyx_type_9debathena_7metrics_9connector_ExecProcEvent;
  __pyx_type_9debathena_7metrics_9connector_UidProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_UidProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "UidProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_UidProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_UidProcEvent = &__pyx_type_9debathena_7metrics_9connector_UidProcEvent;
  __pyx_type_9debathena_7metrics_9connector_GidProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_GidProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "GidProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_GidProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 178; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_GidProcEvent = &__pyx_type_9debathena_7metrics_9connector_GidProcEvent;
  __pyx_type_9debathena_7metrics_9connector_ExitProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_ExitProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ExitProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_ExitProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 192; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_ExitProcEvent = &__pyx_type_9debathena_7metrics_9connector_ExitProcEvent;
  __pyx_type_9debathena_7metrics_9connector_UnknownProcEvent.tp_base = __pyx_ptype_9debathena_7metrics_9connector_ProcEvent;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_UnknownProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "UnknownProcEvent", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_UnknownProcEvent) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_UnknownProcEvent = &__pyx_type_9debathena_7metrics_9connector_UnknownProcEvent;
  __pyx_type_9debathena_7metrics_9connector_Connector.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_9debathena_7metrics_9connector_Connector) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Connector", (PyObject *)&__pyx_type_9debathena_7metrics_9connector_Connector) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_ptype_9debathena_7metrics_9connector_Connector = &__pyx_type_9debathena_7metrics_9connector_Connector;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":119 */
  __pyx_1 = PyInt_FromLong(PROC_EVENT_NONE); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PROC_EVENT_NONE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":120 */
  __pyx_1 = PyInt_FromLong(PROC_EVENT_FORK); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PROC_EVENT_FORK, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":121 */
  __pyx_1 = PyInt_FromLong(PROC_EVENT_EXEC); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PROC_EVENT_EXEC, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":122 */
  __pyx_1 = PyInt_FromLong(PROC_EVENT_UID); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PROC_EVENT_UID, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":123 */
  __pyx_1 = PyInt_FromLong(PROC_EVENT_GID); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PROC_EVENT_GID, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":124 */
  __pyx_1 = PyInt_FromLong(PROC_EVENT_EXIT); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PROC_EVENT_EXIT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/coredump/tmp/trunk/debathena/debathena/metrics/debathena/metrics/connector.pyx":266 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("debathena.metrics.connector");
}

static char *__pyx_filenames[] = {
  "connector.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
